### basic settings

# site properties and page defaults
title: IDEAS Lab
description: IDEAS is an interdisciplinary research lab at Purdue CS, working on modeling the 'human' and 'social' aspects using AI in Robotics, Computer Graphics and AR/VR
logo: images/logo.png
header: images/background.jpg
footer: images/background-footer.jpg
baseurl: /

# site social media and other links
links:
  email: ab@cs.purdue.edu
  github: your-lab
  twitter: IDEASPurdue
  # google-scholar: Jane Smith
  # instagram: YourLabHandle
  # youtube: YourLabChannel

### advanced settings

# automatic citations
auto-cite:
  plugins:
    - name: sources
      input:
        - ../_data/sources.yaml
    # - name: orcid
      # input:
        # - ../_data/orcid.yaml
  output: ../_data/citations.yaml

# default front matter parameters for markdown files
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

# collections
collections:
  members:
    output: true

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# plugins
plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
  # - jekyll-github-metadata
  # - jekyll-avatar
  # - jekyll-gist
  # - jekyll-mentions
  # - jekyll-relative-links
  # - jemoji

# jekyll theme
theme: null
